import type { MixItem, SimCustomer } from "./ctx";

/**
 * Cartera de clientes del seed de presentación: los 5 del relevamiento + 18 nuevos entre kioscos,
 * dietéticas, bares, clubes y un supermercado más, en Rosario, Funes y Pueblo Esther.
 * Los nombres de los nuevos son inventados (no corresponden a comercios reales).
 */
const m = (product: string, min: number, max: number, step: number, prob = 1): MixItem => ({
  product,
  min,
  max,
  step,
  prob,
});

type Def = Omit<SimCustomer, "id"> & { address: string; whatsapp: string; legalName?: string };

export const CUSTOMER_DEFS: Def[] = [
  // --- Los 5 del relevamiento (ya existen en los maestros) ---------------------------------
  {
    key: "arcoiris",
    name: "Supermercado Arcoiris",
    channel: "supermarket",
    zone: "rosario",
    priceList: "super",
    terms: 15,
    weekdays: [1],
    intervalDays: 7,
    mix: [
      m("tap500", 30, 70, 10),
      m("len500", 20, 60, 10),
      m("sur500", 10, 30, 10, 0.6),
      m("ari500", 10, 20, 10, 0.25),
    ],
    pay: "transfer",
    lag: [0, 5],
    contacts: ["Gustavo (depósito)", "Marta"],
    address: "Av. Pellegrini 2310, Rosario",
    whatsapp: "+54 9 341 555-0141",
  },
  {
    key: "lareina",
    name: "Supermercado La Reina",
    channel: "supermarket",
    zone: "rosario",
    priceList: "super",
    terms: 30,
    weekdays: [3],
    intervalDays: 10,
    mix: [m("tap500", 60, 100, 10), m("len500", 50, 90, 10), m("sur500", 10, 30, 10, 0.7)],
    pay: "check30",
    lag: [0, 0],
    contacts: ["Recepción de mercadería", "Hugo"],
    address: "Bv. Oroño 1180, Rosario",
    whatsapp: "+54 9 341 555-0142",
  },
  {
    key: "esperanza",
    name: "La Esperanza",
    channel: "reseller",
    zone: "funes",
    priceList: "mayorista",
    terms: 0,
    weekdays: [2],
    intervalDays: 7,
    mix: [m("sur500", 20, 30, 5), m("tap500", 10, 20, 5, 0.7), m("ari500", 5, 10, 5, 0.3)],
    pay: "on_delivery",
    lag: [0, 0],
    contacts: ["Norma", "Claudio"],
    address: "Av. Santa Fe 440, Funes",
    whatsapp: "+54 9 341 555-0143",
  },
  {
    key: "nautico",
    name: "Club Náutico",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 7,
    weekdays: [5],
    intervalDays: 8,
    mix: [m("len5k", 1, 2, 1), m("tap5k", 1, 1, 1, 0.8), m("tap500", 10, 20, 5, 0.5)],
    pay: "transfer",
    lag: [2, 9],
    contacts: ["Secretaría del club", "Fabián (cocina)"],
    address: "Costanera Sur 85, Rosario",
    whatsapp: "+54 9 341 555-0144",
  },
  {
    key: "viadolce",
    name: "Vía Dolce",
    channel: "reseller",
    zone: "pesther",
    priceList: "mayorista",
    terms: 0,
    weekdays: [4],
    intervalDays: 7,
    mix: [m("tap500", 20, 35, 5), m("len500", 10, 20, 5), m("sur500", 5, 10, 5, 0.4)],
    pay: "on_delivery",
    lag: [0, 0],
    contacts: ["Lorena", "Ezequiel"],
    address: "Ruta 9 km 306, Pueblo Esther",
    whatsapp: "+54 9 341 555-0145",
  },
  // --- Nuevos -------------------------------------------------------------------------------------------
  {
    key: "delparque",
    name: "Supermercado Del Parque",
    channel: "supermarket",
    zone: "funes",
    priceList: "super",
    terms: 15,
    weekdays: [2],
    intervalDays: 7,
    mix: [m("tap500", 20, 40, 10), m("len500", 10, 30, 10), m("sur500", 0, 20, 10, 0.5)],
    pay: "transfer",
    lag: [1, 6],
    contacts: ["Nicolás (encargado)", "Depósito"],
    address: "Av. Rosario 1020, Funes",
    whatsapp: "+54 9 341 555-0146",
    start: "2026-06-30",
  },
  {
    key: "trebol",
    name: "Kiosco El Trébol",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 0,
    weekdays: [1],
    intervalDays: 7,
    mix: [m("tap500", 10, 20, 5), m("len500", 5, 10, 5), m("sur500", 0, 10, 5, 0.4)],
    pay: "on_delivery",
    lag: [0, 0],
    contacts: ["Ramiro"],
    address: "Mendoza 3260, Rosario",
    whatsapp: "+54 9 341 555-0147",
  },
  {
    key: "naturaleza",
    name: "Dietética Naturaleza Viva",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 7,
    weekdays: [5],
    intervalDays: 7,
    mix: [
      m("tap500", 15, 25, 5),
      m("len500", 10, 20, 5),
      m("ari500", 5, 10, 5, 0.6),
      m("sur500", 0, 15, 5, 0.4),
    ],
    pay: "transfer",
    lag: [0, 6],
    contacts: ["Verónica", "Julián"],
    address: "Córdoba 2845, Rosario",
    whatsapp: "+54 9 341 555-0148",
  },
  {
    key: "grano",
    name: "Dietética Grano de Oro",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 7,
    weekdays: [1],
    intervalDays: 9,
    mix: [m("tap500", 15, 30, 5), m("len500", 10, 20, 5), m("ari500", 5, 10, 5, 0.5)],
    pay: "transfer",
    lag: [3, 10],
    contacts: ["Silvana"],
    address: "San Luis 1790, Rosario",
    whatsapp: "+54 9 341 555-0149",
    start: "2026-07-06",
  },
  {
    key: "losamigos",
    name: "Bar Los Amigos",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 0,
    weekdays: [3],
    intervalDays: 8,
    mix: [m("tap5k", 1, 3, 1), m("len5k", 1, 3, 1), m("ari5k", 0, 1, 1, 0.3)],
    pay: "on_delivery",
    lag: [0, 0],
    contacts: ["Beto (dueño)", "Cocina"],
    address: "Sarmiento 1655, Rosario",
    whatsapp: "+54 9 341 555-0150",
  },
  {
    key: "elcruce",
    name: "Bar El Cruce",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 0,
    weekdays: [5],
    intervalDays: 10,
    mix: [m("len5k", 1, 2, 1), m("tap5k", 1, 2, 1)],
    pay: "on_delivery",
    lag: [0, 0],
    unpaidLast: 1,
    contacts: ["Mozo de turno", "Pablo"],
    address: "Alvear 940, Rosario",
    whatsapp: "+54 9 341 555-0151",
  },
  {
    key: "barriosur",
    name: "Club Barrio Sur",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 15,
    weekdays: [1],
    intervalDays: 14,
    mix: [m("tap5k", 2, 3, 1), m("len5k", 2, 3, 1), m("tap500", 20, 30, 10), m("len500", 10, 20, 10, 0.6)],
    pay: "check",
    lag: [14, 30],
    contacts: ["Tesorería", "Mario (buffet)"],
    address: "Av. Francia 3105, Rosario",
    whatsapp: "+54 9 341 555-0152",
  },
  {
    key: "donpepe",
    name: "Rotisería Don Pepe",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 0,
    weekdays: [3],
    intervalDays: 7,
    mix: [m("tap500", 10, 25, 5), m("len500", 10, 20, 5)],
    pay: "on_delivery",
    lag: [0, 0],
    invoiceB: true,
    contacts: ["Pepe"],
    address: "Dorrego 1420, Rosario",
    whatsapp: "+54 9 341 555-0153",
  },
  {
    key: "espiga",
    name: "Panadería La Espiga",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 7,
    weekdays: [5],
    intervalDays: 7,
    mix: [m("tap500", 20, 35, 5), m("len500", 15, 30, 5), m("sur500", 0, 15, 5, 0.4)],
    pay: "transfer",
    lag: [0, 5],
    contacts: ["Mostrador", "Carolina"],
    address: "Entre Ríos 2210, Rosario",
    whatsapp: "+54 9 341 555-0154",
  },
  {
    key: "tiobeto",
    name: "Kiosco Tío Beto",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 0,
    weekdays: [3],
    intervalDays: 8,
    mix: [m("tap500", 10, 15, 5), m("len500", 5, 10, 5)],
    pay: "on_delivery",
    lag: [0, 0],
    invoiceB: true,
    stop: "2026-09-08",
    contacts: ["Beto"],
    address: "Güemes 2780, Rosario",
    whatsapp: "+54 9 341 555-0155",
  },
  {
    key: "sabornatural",
    name: "Dietética Sabor Natural",
    channel: "reseller",
    zone: "rosario",
    priceList: "mayorista",
    terms: 7,
    weekdays: [1],
    intervalDays: 9,
    mix: [m("tap500", 15, 25, 5), m("len500", 10, 20, 5)],
    pay: "transfer",
    lag: [5, 12],
    unpaidLast: 2,
    stop: "2026-09-04",
    contacts: ["Andrea"],
    address: "Rioja 1895, Rosario",
    whatsapp: "+54 9 341 555-0156",
  },
  {
    key: "funescentro",
    name: "Kiosco Funes Centro",
    channel: "reseller",
    zone: "funes",
    priceList: "mayorista",
    terms: 0,
    weekdays: [2],
    intervalDays: 7,
    mix: [m("tap500", 10, 20, 5), m("len500", 5, 15, 5)],
    pay: "on_delivery",
    lag: [0, 0],
    invoiceB: true,
    contacts: ["Gaby"],
    address: "Hipólito Yrigoyen 310, Funes",
    whatsapp: "+54 9 341 555-0157",
  },
  {
    key: "vidasana",
    name: "Dietética Vida Sana",
    channel: "reseller",
    zone: "funes",
    priceList: "mayorista",
    terms: 7,
    weekdays: [2],
    intervalDays: 8,
    mix: [
      m("tap500", 15, 30, 5),
      m("len500", 10, 20, 5),
      m("ari500", 5, 10, 5, 0.5),
      m("sur500", 5, 15, 5, 0.5),
    ],
    pay: "transfer",
    lag: [0, 7],
    contacts: ["Lucía", "Martín"],
    address: "Av. San Martín 560, Funes",
    whatsapp: "+54 9 341 555-0158",
  },
  {
    key: "losalamos",
    name: "Club de Campo Los Álamos",
    channel: "reseller",
    zone: "funes",
    priceList: "mayorista",
    terms: 15,
    weekdays: [2],
    intervalDays: 14,
    mix: [m("tap5k", 3, 4, 1), m("len5k", 3, 4, 1), m("tap500", 20, 40, 10), m("len500", 10, 20, 10, 0.6)],
    pay: "check",
    lag: [0, 6],
    bouncesCheck: true,
    contacts: ["Administración", "Cocina del club house"],
    address: "Camino de los Álamos s/n, Funes",
    whatsapp: "+54 9 341 555-0159",
  },
  {
    key: "doncarlos",
    name: "Almacén Don Carlos",
    channel: "reseller",
    zone: "pesther",
    priceList: "mayorista",
    terms: 0,
    weekdays: [4],
    intervalDays: 7,
    mix: [m("tap500", 10, 20, 5), m("len500", 5, 15, 5), m("sur500", 0, 10, 5, 0.3)],
    pay: "on_delivery",
    lag: [0, 0],
    contacts: ["Don Carlos", "Mirta"],
    address: "Ruta 9 y San Martín, Pueblo Esther",
    whatsapp: "+54 9 341 555-0160",
  },
  {
    key: "kioscoesther",
    name: "Kiosco Esther",
    channel: "reseller",
    zone: "pesther",
    priceList: "mayorista",
    terms: 0,
    weekdays: [4],
    intervalDays: 10,
    mix: [m("tap500", 10, 15, 5), m("len500", 5, 10, 5)],
    pay: "on_delivery",
    lag: [0, 0],
    invoiceB: true,
    stop: "2026-09-05",
    contacts: ["Esther"],
    address: "Belgrano 125, Pueblo Esther",
    whatsapp: "+54 9 341 555-0161",
  },
  {
    key: "pueblover",
    name: "Dietética Pueblo Verde",
    channel: "reseller",
    zone: "pesther",
    priceList: "mayorista",
    terms: 7,
    weekdays: [4],
    intervalDays: 7,
    mix: [m("tap500", 15, 25, 5), m("len500", 10, 20, 5), m("ari500", 5, 10, 5, 0.5)],
    pay: "transfer",
    lag: [1, 8],
    contacts: ["Romina"],
    address: "Sarmiento 78, Pueblo Esther",
    whatsapp: "+54 9 341 555-0162",
  },
  {
    key: "clubpe",
    name: "Club Atlético Pueblo Esther",
    channel: "reseller",
    zone: "pesther",
    priceList: "mayorista",
    terms: 15,
    weekdays: [4],
    intervalDays: 14,
    mix: [m("tap5k", 2, 3, 1), m("len5k", 2, 3, 1), m("tap500", 15, 30, 5)],
    pay: "check",
    lag: [4, 12],
    contacts: ["Tesorería", "Comisión de fiestas"],
    address: "Av. del Club 400, Pueblo Esther",
    whatsapp: "+54 9 341 555-0163",
  },
];

export const EXISTING_CUSTOMER_KEYS = new Set(["arcoiris", "lareina", "esperanza", "nautico", "viadolce"]);
