/**
 * Datos maestros tomados del relevamiento del 30/09/2026 (docs/relevamiento.md).
 * Lo marcado "SUPUESTO" no está en el relevamiento y debe validarse con la empresa.
 */

/** Credenciales SOLO de desarrollo/test. En producción se crean usuarios reales. */
export const DEV_PASSWORD = "chipa1234";

export const USERS = [
  {
    key: "nahuel",
    name: "Nahuel",
    initials: "N.",
    username: "nahuel",
    email: "nahuel@chipacheese.test",
    role: "admin",
    pin: null,
  },
  {
    key: "af",
    name: "A.F. (Jefa de producción)",
    initials: "A.F.",
    username: "af",
    email: "produccion@chipacheese.test",
    role: "production_manager",
    pin: "1111",
  },
  {
    key: "padre",
    name: "Logística (chofer)",
    initials: "P.",
    username: "logistica",
    email: "logistica@chipacheese.test",
    role: "logistics",
    pin: "2222",
  },
  { key: "jt", name: "J.T.", initials: "J.T.", username: "jt", email: null, role: "operator", pin: "1234" },
  { key: "sg", name: "S.G.", initials: "S.G.", username: "sg", email: null, role: "operator", pin: "2345" },
  { key: "ea", name: "E.A.", initials: "E.A.", username: "ea", email: null, role: "operator", pin: "3456" },
  { key: "sr", name: "S.R.", initials: "S.R.", username: "sr", email: null, role: "operator", pin: "4567" },
  {
    key: "local1",
    name: "Local — Empleada 1",
    initials: "L1",
    username: "local1",
    email: "local@chipacheese.test",
    role: "store",
    pin: "5555",
  },
  {
    key: "local2",
    name: "Local — Empleada 2",
    initials: "L2",
    username: "local2",
    email: null,
    role: "store",
    pin: "6666",
  },
  // SUPUESTO: N.R. firma los registros BPM como supervisor; se modela como jefa/supervisión hasta validar.
  {
    key: "nr",
    name: "N.R. (Supervisor de registros)",
    initials: "N.R.",
    username: "nr",
    email: "supervision@chipacheese.test",
    role: "production_manager",
    pin: "7777",
  },
  {
    key: "rt",
    name: "Responsable técnico",
    initials: "RT",
    username: "rtecnico",
    email: "rt@chipacheese.test",
    role: "technical_lead",
    pin: null,
  },
  {
    key: "contadora",
    name: "Contadora",
    initials: "CT",
    username: "contadora",
    email: "contadora@chipacheese.test",
    role: "accountant",
    pin: null,
  },
] as const;

export const SETTINGS: Record<string, { value: unknown; description: string }> = {
  "production.daily_capacity_kg": { value: 150, description: "Techo diario por el abatidor (Regla 1)" },
  "production.min_batch_kg": { value: 75, description: "Mínimo de producto por tanda (Regla 1)" },
  "production.shelf_life_months": { value: 6, description: "Vida útil congelado" },
  "production.workdays": {
    value: [1, 2, 3, 4, 5],
    description: "Días de producción (SUPUESTO: lunes a viernes, 22 días/mes)",
  },
  "production.consumption_threshold_pct": {
    value: 10,
    description: "Desvío consumo real vs teórico que dispara aviso (Regla 2, a definir)",
  },
  "labor.workers": { value: 4, description: "Operarios por producción" },
  "labor.hours_per_run": { value: 6, description: "Horas por producción" },
  "labor.hourly_cost": { value: 5000, description: "Costo hora (dato del Excel, parece desactualizado)" },
  "orders.overdue_factor": {
    value: 1.5,
    description: "Aviso 'cliente sin pedir' cuando pasan X veces su frecuencia",
  },
  "orders.max_weekly_capacity_pct": {
    value: 50,
    description: "Aviso si un pedido ocupa más de este % de la capacidad semanal de producción (RF-05)",
  },
  "store.target_days": {
    value: 3,
    description: "Días de venta que debe cubrir una reposición del local (alertas de stock del local)",
  },
  "store.replenish_lead_days": {
    value: 1,
    description: "Días que tarda la planta en reponer el local (alertas de stock del local)",
  },
  "delivery.driver_hourly_cost": { value: 5000, description: "Costo hora chofer (SUPUESTO)" },
  "company.name": { value: "Pacon SRL — Chipa Cheese", description: "Razón social" },
};

export const ZONES = [
  // SUPUESTO: días por zona, se fijan en la Fase 1.
  { key: "rosario", name: "Rosario", deliveryWeekdays: [1, 3, 5] },
  { key: "funes", name: "Funes", deliveryWeekdays: [2] },
  { key: "pesther", name: "Pueblo Esther", deliveryWeekdays: [4] },
];

export const SUPPLIERS = [
  {
    key: "leopelle",
    legalName: "Leo Pelle",
    leadTimeDays: 2,
    notes: "Quesos barra y reggianito, fécula, sal, leche, manteca, queso feteado",
  },
  { key: "cotar", legalName: "Cotar", leadTimeDays: 1, notes: "Leche" },
  { key: "mancinelli", legalName: "Mancinelli", leadTimeDays: 2, notes: "Huevo, jamón" },
  { key: "jorge", legalName: "Jorge (manteca)", leadTimeDays: 2, notes: "Manteca" },
];

/** Insumos con precio sin IVA al 29/09/2026 (pestaña de costeo). */
export const INGREDIENTS = [
  {
    key: "queso_barra",
    name: "Queso barra (Tybo/Maki)",
    category: "dairy",
    unit: "kg",
    refrigerated: true,
    supplier: "leopelle",
    price: 9880,
    minStock: 25,
  },
  {
    key: "reggianito",
    name: "Queso reggianito",
    category: "dairy",
    unit: "kg",
    refrigerated: true,
    supplier: "leopelle",
    price: 13431,
    minStock: 15,
  },
  {
    key: "manteca",
    name: "Manteca",
    category: "fat",
    unit: "kg",
    refrigerated: true,
    supplier: "jorge",
    price: 9800,
    minStock: 15,
  },
  {
    key: "fecula",
    name: "Fécula de mandioca",
    category: "starch",
    unit: "kg",
    refrigerated: false,
    supplier: "leopelle",
    price: 1728,
    minStock: 75,
  },
  {
    key: "huevo",
    name: "Huevo",
    category: "egg",
    unit: "kg",
    refrigerated: true,
    supplier: "mancinelli",
    price: 3222,
    minStock: 18,
  },
  {
    key: "leche",
    name: "Leche",
    category: "dairy",
    unit: "l",
    refrigerated: true,
    supplier: "cotar",
    price: 1066,
    minStock: 30,
  },
  {
    key: "sal",
    name: "Sal",
    category: "seasoning",
    unit: "kg",
    refrigerated: false,
    supplier: "leopelle",
    price: 708,
    minStock: 3,
  },
  {
    key: "bolsa500",
    name: "Bolsa 0,5 kg con etiqueta",
    category: "packaging",
    unit: "unit",
    refrigerated: false,
    supplier: null,
    price: 140,
    minStock: 500,
  },
  {
    key: "bolsa5k",
    name: "Bolsa granel 5 kg",
    category: "packaging",
    unit: "unit",
    refrigerated: false,
    supplier: null,
    price: null,
    minStock: 50,
  },
  {
    key: "jamon",
    name: "Jamón feteado",
    category: "filling",
    unit: "kg",
    refrigerated: true,
    supplier: "mancinelli",
    price: null,
    minStock: 2,
  },
  {
    key: "queso_feteado",
    name: "Queso feteado",
    category: "filling",
    unit: "kg",
    refrigerated: true,
    supplier: "leopelle",
    price: null,
    minStock: 2,
  },
] as const;

/**
 * Receta maestra v1 por kg de fécula. Cantidades del Excel 29/09; rangos según los registros
 * de elaboración del 26/08 y 01/09 (leche 18–30 L, manteca 10–15 kg, sal 1,9–2,25 kg).
 * Estado "active" hasta que se valide en planta (Fase 1).
 */
export const RECIPE_V1 = {
  name: "Masa de chipá",
  version: 1,
  expectedYieldPerKgStarch: 1.99, // 149,3 kg / 75 kg (registro 01/09)
  deviationThresholdPct: 10,
  notes:
    "v1 cargada desde el Excel 29/09 con rangos de los registros 26/08 y 01/09. Validar pesando 3 producciones.",
  items: [
    {
      ingredient: "fecula",
      qty: 1,
      min: null,
      max: null,
      instructions: "Pesar 75 kg en dos tandas de 37,5 kg",
    },
    { ingredient: "queso_barra", qty: 0.3, min: 0.2933, max: 0.3, instructions: "Cortado de queso barra" },
    { ingredient: "reggianito", qty: 0.2, min: 0.2, max: 0.2, instructions: "Rallado de reggianito" },
    { ingredient: "manteca", qty: 0.2, min: 0.1333, max: 0.2, instructions: "Pesar y ablandar" },
    { ingredient: "huevo", qty: 0.24, min: 0.24, max: 0.24, instructions: "Batir en batidora" },
    {
      ingredient: "leche",
      qty: 0.4,
      min: 0.24,
      max: 0.4,
      instructions: "Ajustar por textura dentro del rango (criterio a escribir)",
    },
    { ingredient: "sal", qty: 0.03, min: 0.0253, max: 0.03, instructions: "Dosificar en la batidora" },
  ],
} as const;

export const PRODUCTS = [
  {
    key: "tap500",
    code: "CH-TAP-500",
    name: "Chipá tapitas 0,5 kg",
    shape: "tapita",
    presentation: "bag_500g",
    netWeightKg: 0.5,
    boardCode: "C500",
    minStock: 60,
    packaging: [["bolsa500", 1]],
  },
  {
    key: "ari500",
    code: "CH-ARI-500",
    name: "Chipá aritos 0,5 kg",
    shape: "arito",
    presentation: "bag_500g",
    netWeightKg: 0.5,
    boardCode: "C500",
    minStock: 20,
    packaging: [["bolsa500", 1]],
  },
  {
    key: "len500",
    code: "CH-LEN-500",
    name: "Chipá lengüitas 0,5 kg",
    shape: "lenguita",
    presentation: "bag_500g",
    netWeightKg: 0.5,
    boardCode: "C500",
    minStock: 60,
    packaging: [["bolsa500", 1]],
  },
  {
    key: "sur500",
    code: "CH-SUR-500",
    name: "Chipá surtido 0,5 kg",
    shape: "mixed",
    presentation: "bag_500g",
    netWeightKg: 0.5,
    boardCode: "C500",
    minStock: 40,
    packaging: [["bolsa500", 1]],
  },
  {
    key: "tap5k",
    code: "CH-TAP-5K",
    name: "Chipá tapitas granel 5 kg",
    shape: "tapita",
    presentation: "bulk_5kg",
    netWeightKg: 5,
    boardCode: "C granel",
    minStock: 4,
    packaging: [["bolsa5k", 1]],
  },
  {
    key: "ari5k",
    code: "CH-ARI-5K",
    name: "Chipá aritos granel 5 kg",
    shape: "arito",
    presentation: "bulk_5kg",
    netWeightKg: 5,
    boardCode: "C granel",
    minStock: 2,
    packaging: [["bolsa5k", 1]],
  },
  {
    key: "len5k",
    code: "CH-LEN-5K",
    name: "Chipá lengüitas granel 5 kg",
    shape: "lenguita",
    presentation: "bulk_5kg",
    netWeightKg: 5,
    boardCode: "C granel",
    minStock: 4,
    packaging: [["bolsa5k", 1]],
  },
  // Sándwich: ~180 g de masa + 5 fetas de jamón (100 g) + 6 fetas de queso (100 g).
  {
    key: "sw",
    code: "SW-JYQ",
    name: "Chisanwich JyQ (pack)",
    shape: "sandwich",
    presentation: "pack",
    netWeightKg: 0.18,
    boardCode: "SW",
    minStock: 20,
    packaging: [
      ["jamon", 0.1],
      ["queso_feteado", 0.1],
    ],
  },
  {
    key: "pz",
    code: "PZ-REC",
    name: "Pizzetas (recorte de masa)",
    shape: "pizzeta",
    presentation: "unit",
    netWeightKg: 0.1,
    boardCode: null,
    minStock: 0,
    packaging: [],
  },
] as const;

export const PRICE_LISTS = [
  {
    key: "mayorista",
    name: "Revendedores (mayorista)",
    channel: "reseller",
    targetMarginPct: 25,
    prices: {
      tap500: 4200,
      ari500: 4200,
      len500: 4200,
      sur500: 4200,
      tap5k: 40000,
      ari5k: 40000,
      len5k: 40000,
      sw: 2600,
    },
  },
  // SUPUESTO: precio a supermercados no relevado ("más bajo que revendedor").
  {
    key: "super",
    name: "Supermercados",
    channel: "supermarket",
    targetMarginPct: 18,
    prices: {
      tap500: 3900,
      ari500: 3900,
      len500: 3900,
      sur500: 3900,
      tap5k: 37000,
      ari5k: 37000,
      len5k: 37000,
      sw: 2400,
    },
  },
  {
    key: "local",
    name: "Local (minorista)",
    channel: "store",
    targetMarginPct: 33,
    prices: {
      tap500: 4800,
      ari500: 4800,
      len500: 4800,
      sur500: 4800,
      tap5k: 46000,
      ari5k: 46000,
      len5k: 46000,
      sw: 3000,
      pz: 1500,
    },
  },
] as const;

export const LOCATIONS = [
  { key: "seco", code: "DEP-SECO", name: "Depósito seco", kind: "raw", capacityKg: null },
  {
    key: "heladera",
    code: "HELADERA",
    name: "Heladera vertical (materia prima)",
    kind: "raw",
    capacityKg: null,
  },
  { key: "f3", code: "F3", name: "Freezer horizontal F3", kind: "finished", capacityKg: null },
  { key: "f4", code: "F4", name: "Freezer horizontal F4", kind: "finished", capacityKg: null },
  { key: "local", code: "LOCAL", name: "Local comercial", kind: "store", capacityKg: null },
  { key: "vehiculo", code: "VEHICULO", name: "Vehículo de reparto", kind: "vehicle", capacityKg: null },
] as const;

export const EQUIPMENT = [
  {
    key: "batidora",
    code: "BATIDORA",
    name: "Batidora",
    area: "Elaboración",
    kind: "machine",
    min: null,
    max: null,
  },
  {
    key: "amasadora",
    code: "AMASADORA",
    name: "Amasadora",
    area: "Elaboración",
    kind: "machine",
    min: null,
    max: null,
  },
  {
    key: "biscomatic",
    code: "BISCOMATIC",
    name: "Formadora Biscomatic",
    area: "Elaboración",
    kind: "machine",
    min: null,
    max: null,
  },
  {
    key: "f1",
    code: "F1",
    name: "Freezer vertical F1 (abatidor)",
    area: "Congelado",
    kind: "freezer",
    min: null,
    max: -18,
  },
  {
    key: "f2",
    code: "F2",
    name: "Freezer vertical F2 (abatidor)",
    area: "Congelado",
    kind: "freezer",
    min: null,
    max: -18,
  },
  {
    key: "f3",
    code: "F3",
    name: "Freezer horizontal F3",
    area: "Almacenamiento",
    kind: "freezer",
    min: null,
    max: -18,
    location: "f3",
  },
  {
    key: "f4",
    code: "F4",
    name: "Freezer horizontal F4",
    area: "Almacenamiento",
    kind: "freezer",
    min: null,
    max: -18,
    location: "f4",
  },
  {
    key: "heladera",
    code: "HELADERA",
    name: "Heladera vertical",
    area: "Materia prima",
    kind: "fridge",
    min: 0,
    max: 5,
    location: "heladera",
  },
  {
    key: "selladora",
    code: "SELLADORA",
    name: "Selladora neumática",
    area: "Envasado",
    kind: "machine",
    min: null,
    max: null,
  },
  {
    key: "balanza",
    code: "BALANZA",
    name: "Balanza de envasado",
    area: "Envasado",
    kind: "machine",
    min: null,
    max: null,
  },
  {
    key: "rallador",
    code: "RALLADOR",
    name: "Rallador de queso",
    area: "Preproducción",
    kind: "machine",
    min: null,
    max: null,
  },
  {
    key: "vehiculo",
    code: "VEH-FRIO",
    name: "Equipo de frío del vehículo",
    area: "Reparto",
    kind: "vehicle",
    min: null,
    max: -18,
    location: "vehiculo",
  },
] as const;

/** Matriz de tareas del pizarrón. `people`: quién la hace hoy; `critical`: una sola persona sabe. */
export const PLANT_TASKS = [
  { stage: "preproduction", name: "Cortado y rallado de queso reggianito", people: ["jt"], critical: true },
  { stage: "preproduction", name: "Huevos", people: ["sg", "ea"], critical: false },
  { stage: "preproduction", name: "Cortado de queso barra", people: ["sg", "sr"], critical: false },
  { stage: "preproduction", name: "Manteca", people: ["sg", "sr", "ea"], critical: false },
  { stage: "preproduction", name: "Leche (dosificación)", people: ["af"], critical: true },
  { stage: "preproduction", name: "Sal (dosificación)", people: ["af"], critical: true },
  { stage: "preproduction", name: "Mandioca (fécula)", people: ["jt", "ea"], critical: false },
  { stage: "machines", name: "Batidora", people: ["af"], critical: true },
  { stage: "machines", name: "Amasadora", people: ["ea"], critical: true },
  { stage: "machines", name: "Biscomatic: manejo", people: ["ea"], critical: true },
  { stage: "machines", name: "Biscomatic: recepción", people: ["sg", "sr"], critical: false },
  { stage: "machines", name: "Biscomatic: acomodo en bandejas", people: ["jt"], critical: false },
  { stage: "finishing", name: "Retiro y embolsado a granel", people: ["sg", "sr"], critical: false },
  { stage: "finishing", name: "Sellado y loteado", people: ["af", "ea", "sg", "sr"], critical: false },
  { stage: "finishing", name: "Acopio en freezer", people: ["jt"], critical: true },
  {
    stage: "cleaning",
    name: "Limpieza moldes, útiles, batidora y bandejas",
    people: ["jt"],
    critical: false,
  },
  { stage: "cleaning", name: "Limpieza amasadora y sector", people: ["ea"], critical: false },
  { stage: "cleaning", name: "Limpieza Biscomatic", people: ["sr"], critical: false },
  { stage: "cleaning", name: "Limpieza F1 y F2 (semanal)", people: ["jt", "ea"], critical: false },
  { stage: "cleaning", name: "Pisos (rotativo)", people: ["jt", "sg", "ea", "sr"], critical: false },
] as const;

export const SANITATION_POINTS = [
  { sector: "Elaboración", element: "Moldes y útiles", frequency: "daily" },
  { sector: "Elaboración", element: "Batidora", frequency: "daily", equipment: "batidora" },
  { sector: "Elaboración", element: "Bandejas", frequency: "daily" },
  { sector: "Elaboración", element: "Amasadora y sector", frequency: "daily", equipment: "amasadora" },
  { sector: "Elaboración", element: "Biscomatic", frequency: "daily", equipment: "biscomatic" },
  { sector: "Congelado", element: "Freezer F1", frequency: "weekly", equipment: "f1" },
  { sector: "Congelado", element: "Freezer F2", frequency: "weekly", equipment: "f2" },
  { sector: "General", element: "Pisos", frequency: "daily" },
  { sector: "Envasado", element: "Selladora y balanza", frequency: "daily", equipment: "selladora" },
] as const;

/** SUPUESTO: frecuencias propuestas; el registro actual no tiene plan. */
export const MAINTENANCE_PLANS = [
  { equipment: "biscomatic", task: "Revisión y cambio de alambre de corte", frequencyDays: 30 },
  { equipment: "biscomatic", task: "Lubricación y ajuste general", frequencyDays: 90 },
  { equipment: "amasadora", task: "Revisión de correas y lubricación", frequencyDays: 90 },
  { equipment: "batidora", task: "Revisión de engranajes y paleta", frequencyDays: 90 },
  { equipment: "f1", task: "Limpieza de condensador y burletes", frequencyDays: 90 },
  { equipment: "f2", task: "Limpieza de condensador y burletes", frequencyDays: 90 },
  { equipment: "f3", task: "Limpieza de condensador y burletes", frequencyDays: 90 },
  { equipment: "f4", task: "Limpieza de condensador y burletes", frequencyDays: 90 },
  { equipment: "vehiculo", task: "Service del equipo de frío", frequencyDays: 180 },
  { equipment: "selladora", task: "Revisión de resistencia y teflón", frequencyDays: 60 },
  { equipment: "balanza", task: "Verificación con pesa patrón", frequencyDays: 30 },
] as const;

/** Gastos fijos de la pestaña de abril (incompletos según el relevamiento). */
export const FIXED_EXPENSES = [
  { concept: "Alquiler", category: "rent", amount: 300000 },
  { concept: "Contadora", category: "professional", amount: 200000 },
  { concept: "Luz", category: "services", amount: 200000 },
  { concept: "ASSAL", category: "taxes", amount: 100000 },
  { concept: "Seguro", category: "insurance", amount: 100000 },
  { concept: "Agua", category: "services", amount: 100000 },
  { concept: "Desinfección", category: "services", amount: 40000 },
] as const;

export const CUSTOMERS = [
  {
    key: "arcoiris",
    legalName: "Supermercado Arcoiris",
    channel: "supermarket",
    priceList: "super",
    zone: "rosario",
    paymentTermsDays: 15,
    whatsapp: null,
  },
  {
    key: "lareina",
    legalName: "Supermercado La Reina",
    channel: "supermarket",
    priceList: "super",
    zone: "rosario",
    paymentTermsDays: 30,
    paymentNotes: "Cheque a 30 días",
    whatsapp: null,
  },
  {
    key: "esperanza",
    legalName: "La Esperanza",
    channel: "reseller",
    priceList: "mayorista",
    zone: "funes",
    paymentTermsDays: 0,
    whatsapp: null,
  },
  {
    key: "nautico",
    legalName: "Club Náutico",
    channel: "reseller",
    priceList: "mayorista",
    zone: "rosario",
    paymentTermsDays: 7,
    whatsapp: null,
  },
  {
    key: "viadolce",
    legalName: "Vía Dolce",
    channel: "reseller",
    priceList: "mayorista",
    zone: "pesther",
    paymentTermsDays: 0,
    whatsapp: null,
  },
  {
    key: "mostrador",
    legalName: "Consumidor final (local)",
    channel: "store",
    priceList: "local",
    zone: null,
    paymentTermsDays: 0,
    whatsapp: null,
  },
] as const;

/**
 * Productos que no salen de la masa en planta (el local vende más que chipá):
 * - resale: reventa (gaseosas, aguas), con su costo de compra.
 * - prepared: elaborado en el local con producto terminado (equivalente en bolsas de un producto base).
 * SUPUESTO: marcas, precios y costos de ejemplo hasta cargar los reales.
 */
export const EXTRA_PRODUCTS = [
  {
    key: "gaseosa500",
    code: "RV-GAS-500",
    name: "Gaseosa 500 ml",
    kind: "resale",
    unitLabel: "botella",
    barcode: "7790895000997",
    storePrice: 1800,
    unitCost: 1100,
    minStock: 24,
  },
  {
    key: "agua500",
    code: "RV-AGU-500",
    name: "Agua mineral 500 ml",
    kind: "resale",
    unitLabel: "botella",
    barcode: "7798062540017",
    storePrice: 1300,
    unitCost: 700,
    minStock: 12,
  },
  {
    key: "horneado250",
    code: "EL-HOR-250",
    name: "Chipá horneado 250 g (para llevar)",
    kind: "prepared",
    unitLabel: "porción",
    barcode: null,
    storePrice: 3200,
    unitCost: null,
    minStock: 0,
    base: { product: "tap500", qty: 0.5 },
    netWeightKg: 0.25,
  },
] as const;
